# The name of this service (as it appears in logs)
service_name: scaffold-demo

# The type of this service (as it appears in logs)
service_type: service-scaffold-golang

# A constant prepended to all URIs
base_uri: /v0

# The IP interface and port to bind the service to
listen_address: localhost
listen_port: 8080
# Log level, one of (in increasing severity): debug, info, warning, error and fatal
log_level: debug
